### PR TITLE
DDSim: Change default tracker action to Geant4TrackerWeightedAction

### PR DESCRIPTION
**Pull request by andresailer**
This is the more sensible default and needed by the track reconstruction. Avoid problems when people don't use steering files

### CODE REVIEW

**Comment by gaede** [comment]
In the ILD  default steering file we use:
`SIM.action.tracker = ("Geant4TrackerWeightedAction", {"HitPositionCombination" : 2 , "CollectSingleDeposits" :  False } )`
Should these options also be used as default ?

**Comment by gaede** [comment]
@andresailer: any comment on the default configuration of the Geant4TrackerWeightedAction ?

**Comment by andresailer** [comment]
HitPositionCombination 2 and CollectSingleDesposits False are the defaults. We could make it explicit if you prefer.

**Comment by gaede** [comment]
I think it would be nice to make this explicit in DDSim if this can be done easily.

**Comment by andresailer** [comment]
Now it is explicit

**Pull request merged**
