### PR TITLE
changed the CartesianGridXZ readout to CartesianGridXY

### PR DESCRIPTION
**Pull request by TiborILD**
BEGINRELEASENOTES
- update of ILD Hcal endcap readout segmentation
        - in order to unify the readouts for all Hcal detectors  the CartesianGridXZ readout of SHCalsc04_Endcaps_v01 was changed to CartesianGridXY readout 
       - affects models ILD_l/s4_v02 and ILD_l/s5_v02

ENDRELEASENOTES

### CODE REVIEW

**Comment by shaojunlu** [comment]
@TiborILD Do you think that it is good to update FEE_half_Y to  FEE_half_y in SHcalSc04_Endcaps_v01.cpp in your PR#157?

**Comment by TiborILD** [comment]
You probably mean going from FEE_half_y to FEE_half_Y?  Yes, it's a part of the modifications.  As well as 
changing  FEE_half_Z to FEE_half_z. I want to avoid mixing of x and z coordinates, see also the changes
in corresponding xml files.

**Comment by shaojunlu** [comment]
@TiborILD 
https://github.com/iLCSoft/lcgeo/pull/157/files#diff-0d89c269f1924dcfd19086705373fce5R214
As I see the line 214 use "FEE_half_Y" with "Y", and line 213 and line 215 both use "FEE_half_x" not "X" and "FEE_half_z" "not "Z".
So I think that you may want to change "FEE_half_Y" at line 214 to "FEE_half_y" not "Y".
inside the cpp code.

**Comment by shaojunlu** [comment]
@TiborILD 
I will have a look at the xml update later too with the cpp driver.

**Comment by TiborILD** [comment]
I just used the same "naming scheme" of variables as in previous version where (x,y,Z) is used se e.g.

213       double FEE_half_x = box_half_x-Hcal_endcap_services_module_width/2.0;
214       double FEE_half_y = box_half_y;
215       double FEE_half_Z = Hcal_endcap_services_module_width/2.0;
216
217       Box    FEEBox(FEE_half_x,FEE_half_y,FEE_half_Z);
218       Volume FEEModule("Hcal_endcap_FEE",FEEBox,air);

    and I have just swapped (FEE_half_Y, FEE_half_z) instead of (FEE_half_y, FEE_half_Z)
     so now we have (x,Y,z)  .

**Comment by shaojunlu** [comment]
@TiborILD 
The previous version (x,y,Z), I think that I made a typo for "Z".
It should be (x,y,z). You may correct it too. Thanks.

**Comment by TiborILD** [comment]
OK,  why not. It's done

**Comment by shaojunlu** [comment]
@TiborILD 
Thanks. 
And would you please change the compact file "SHcalSc04_Endcaps_v01_LARGE.xml" and "SHcalSc04_Endcaps_v01_SMALL.xml", and use this order "dim_x, dim_y, dim_z".
For example here:
https://github.com/iLCSoft/lcgeo/pull/157/files#diff-e70ad4c3cfb21a944b8c83cc5c0d7462R24

**Comment by shaojunlu** [comment]
@TiborILD 
These two comments will not be true any more:
https://github.com/TiborILD/lcgeo/blob/modifGridxz2xy/detector/calorimeter/SHcalSc04_Endcaps_v01.cpp#L192
https://github.com/TiborILD/lcgeo/blob/modifGridxz2xy/detector/calorimeter/SHcalSc04_Endcaps_v01.cpp#L193
Please remove "// total thickness, all are same", which will be true for "dim_z" now from your update.

**Comment by shaojunlu** [comment]
@TiborILD 
We have one official confluence wiki page for ILD simulation.
https://confluence.desy.de/display/ILD/Simulation#Simulation-Geometryvalidationtools:CheckOverlaps
It should be good to perform some validation.
For example for the official release version, and you could check your version too.
. /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-04/init_ilcsoft.sh
geoDisplay -compact lcgeo/ILD/compact/ILD_l4_v02/ILD_l4_v02.xml
root [0] gGeoManager->CheckOverlaps(0.00001)
root [1] gGeoManager->PrintOverlaps();
Thank you very much!

**Comment by TiborILD** [comment]
OK, I have done those validation checks with my version of v01-19-04, i.e. with my modified SHcalSC04_Endcaps_v01.cpp rresp correspondig SMALL & LARGE xml-files.
   I corrected for the found problems and it looks OK now:

1.
geoDisplay -compact ../ILD/compact/ILD_l4_v02/ILD_l4_v02.xml

root [1] gGeoManager->CheckOverlaps(0.00001)
Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for world_volume and daughters within 1e-05
Check overlaps:      [==========]  439083 [100.00 %]           00:10
Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 0

2.
geoDisplay -compact ../ILD/compact/ILD_s4_v02/ILD_s4_v02.xml

root [0] gGeoManager->CheckOverlaps(0.00001)
Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for world_volume and daughters within 1e-05
Check overlaps:      [==========]  361159 [100.00 %]           07
Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 0

**Pull request merged**
