### PR TITLE
Update BeamCal_o2_v03.xml

### PR DESCRIPTION
**Pull request by protopopescu**
Minor corrections

BEGINRELEASENOTES
- Removed some unused parameters
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Please put the detector model in the release notes

**Comment by protopopescu** [comment]
This minor change is part of PR #202; I don't know why you got to see it at all ...

**Comment by andresailer** [comment]
Because you keep creating branches in this repository instead of in you fork.
Also the comment for the detector model applies to your other PR as well

**Comment by protopopescu** [comment]
Thanks, Andre! I’ve added the detector model in the comments for both.
Could you please approve PR #202?

Best regards,
Dan

—
Dr. Dan PROTOPOPESCU, University of Glasgow, UK
W:+44(0)141-330-4197 M:+44(0)794-046-3355
http://ppewww.physics.gla.ac.uk/~protopop/

On 22 Feb 2018, at 15:19, Andre Sailer <notifications@github.com<mailto:notifications@github.com>> wrote:


Because you keep creating branches in this repository instead of in you fork.
Also the comment for the detector model applies to your other PR as well

**Pull request merged**
