### PR TITLE
ILD: new models for 1TeV

### PR DESCRIPTION
**Pull request by danieljeans**
add models with fields for 1TeV in fwd magnets (v07: no antiDID, v08:…… with antiDID)

BEGINRELEASENOTES
- QD0 and QDEX1A magnet strengths for 1 TeV
- new models
  ILD_(sl)5_v07 : 1 TeV fwd magnets, solenoid field map, no anti-DID
  ILD_(sl)5_v08 : 1 TeV fwd magnets, solenoid field map + with anti-DID

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
Should we merge this now ? 
@danieljeans Is it all fine for you ?

**Comment by shaojunlu** [comment]
@rete @danieljeans 
It shows "All checks have passed", does this check is enough?
For the "1 TeV fwd magnets ...", Daniel has already discussed with magnet engineer in KEK, do we need magnet engineer stamp here?

**Comment by shaojunlu** [comment]
@danieljeans 
Do you also want to add the simulation models "ILD_l5_v07", "ILD_l5_v08", "ILD_s5_v07" and "ILD_s5_v08" into this PR, too?
I saw that you have the reconstruction models  "ILD_(s/l)5_o1_v(07/08)" in this PR only.

**Comment by rete** [comment]
@shaojunlu Good point !
@danieljeans Can you please these 4 models ? They are exactly the same as the ones you added but we need them for the production just for naming convention.

**Comment by rete** [comment]
TravisCI problems. See #221

**Pull request merged**
