### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bogdanmishchenko**
Added missing bits for encoding of endcaps from comparison with latest TrackerEndcap_o2_v06_geo.cpp

### CODE REVIEW

**Comment by protopopescu** [comment]
Please correct indentation and white space, and DECLARE_DETELEMENT(SiTrackerEndcap_o2_v01ext,create_detector) should be DECLARE_DETELEMENT(SiTrackerEndcap_o2_v02ext,create_detector).

**Comment by andresailer** [comment]
The second commit placed the file in `detector` not in `detector/tracker` so now the file you want to use is not even being compiled.

**Comment by protopopescu** [comment]
Fixed by patch-1

**Comment by bogdanmishchenko** [comment]
Thanks !

**Pull request merged**
