### PR TITLE
new ILD_l5_v09 models

### PR DESCRIPTION
**Pull request by danieljeans**
BEGINRELEASENOTES
- ILD_l5[_o1,2,3,4]_v09 models with CLIC-inspired all silicon outer tracker in place of TPC+SET
- otherwise identical to ILD_l5_v02 model
ENDRELEASENOTES

### CODE REVIEW

**Comment by tmadlener** [comment]
Hi @danieljeans,

this already includes the fix that you described in the meeting today, right?

**Comment by danieljeans** [comment]
> 

yes, https://github.com/iLCSoft/lcgeo/pull/250/commits/140c4902fdc06cea135617b7c07b59956ba569d5 implements the fix I mentioned (which caused a crash).

**Comment by danieljeans** [comment]
there seem to be a few strange features...please hold back on accepting this pull request

**Comment by tmadlener** [comment]
Thanks for letting us know. I will mark it as a draft. Once everything is understood and this should proceed to be merged you can simply remove that label again.

**Comment by danieljeans** [comment]
@tmadlener I think this is ready for the next devel release.

**Comment by tmadlener** [comment]
Hi @danieljeans, would it be possible to add a test for one of the new detector models, just to at least have a small safety net for future changes here. In principle that should be as simple as adding a few lines here (with the appropriate compact file)

https://github.com/iLCSoft/lcgeo/blob/600905aa3e26a527a10b13b5bd7e822072ec48a8/lcgeoTests/CMakeLists.txt#L18-L21

**Comment by danieljeans** [comment]
> Hi @danieljeans, would it be possible to add a test for one of the new detector models, just to at least have a small safety net for future changes here.

@tmadlener thanks for the suggestion: done.

**Comment by tmadlener** [comment]
The failing CI workflow has been removed (DD4hep no longer builds with gcc8), so we can ignore that. I will remove it in another PR, after merging this.

**Review by tmadlener — APPROVED** [review]

**Pull request merged**
