### PR TITLE
Improve DDSim defaults

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
- Set DDSim defaults to Geant4 defaults and retain `largest_step = 10 * m` as recommended in the Geant4 manual (~ detector size). This improves simulation time for single muons approximately a factor 2 and for single pi+ for 25%

ENDRELEASENOTES

I have made a comparison between what @gaede recommended in AIDASoft/DD4hep#266

```py
SIM.field.delta_chord = 1e-05
SIM.field.delta_intersection = 1e-05
SIM.field.delta_one_step = .5e-03*mm
SIM.field.eps_max = 1e-04
SIM.field.eps_min = 1e-05
SIM.field.equation = "Mag_UsualEqRhs"
SIM.field.largest_step = 10.*m
SIM.field.min_chord_step = 1.e-2*mm
SIM.field.stepper = "HelixSimpleRunge"
```

and the values in this PR. For simulating 10k single muon events I need 13m with the ILD config and 7m with the new defaults.

### CODE REVIEW

**Comment by gaede** [comment]
Perfectly fine to move to Geant4 defaults. But you should not claim that this reduces simulation times by a factor of 2 - this is only for muons, i.e. tracking. Try some electrons and hadrons to see the effective reduction in the simulation time...

**Comment by petricm** [comment]
I have updated the release notes to state that it improves simulation time for muons

**Comment by petricm** [comment]
For completeness for 10GeV pi+ ILDConfig settings are 25% slower (6 min vs 7.5 min)

**Comment by gaede** [comment]
Ok, that is interesting. I would have expected a much smaller difference for hadrons. Anyways we'll test the new settings for the ILD simulation.

**Pull request merged**
