### PR TITLE
Update ECalBarrel_o1_v03_geo.cpp

### PR DESCRIPTION
**Pull request by asteinhebel**
1) Changed layer numbering to start at layer0 with output of layer 0 -> layer 30 (originally was layer 1 -> layer 31)
    2) Fixed hardcoding problem with "mod_z" variable. Needs to be used concurrently with updated main SiD .xml steering file (where for the ECalBarrel, r_min=1264 . Before, r_min=1265 )

### CODE REVIEW

**Comment by protopopescu** [comment]
Removed minor conflict in a comment, and fixed some code indentation

**Comment by andresailer** [comment]
Don't use merging, use rebase.
Also the indentation is now inconsistent.

**Comment by protopopescu** [comment]
Andre, I'm using the browser interface, and I think I only got a "Merge" button there. Same about the indentation: it looked ok in the browser. You suggest using command line for these operations?

**Comment by andresailer** [comment]
Yes, use the command line, or let Amanda rebase her branch

**Comment by protopopescu** [comment]
Ok, is there a way to roll back my edits?

**Comment by andresailer** [comment]
I guess a force push to Amanda's branch will overwrite your change. But I have not a lot of experience with the github web changes.

**Comment by gaede** [comment]
Not sure if I understand the problem or what went wrong here ?
- in the browser interface we have actually only enabled the "rebase and merge"  button, so from there you cannot do a simple "merge"
- in case it says "This branch cannot be rebased due to conflicts" the button is not active and then the person creating the PR needs to do the rebase and resolve the issue

**Comment by andresailer** [comment]
Dan tried to use this feature: https://github.com/blog/2293-resolve-simple-merge-conflicts-on-github

**Comment by gaede** [comment]
Ok, I see. Guess we should discourage the use of this feature then...

**Comment by protopopescu** [comment]
Yes, indeed, that’s what I used. Seemed the obvious step ...

Best regards,
Dan

--
Dan PROTOPOPESCU, University of Glasgow, UK
W:+44(0)141-330-4197 M:+44(0)794-046-3355
http://ppewww.physics.gla.ac.uk/~protopop/

**Comment by protopopescu** [comment]
Since these are only minor changes, it might be easier to start again.

**Comment by andresailer** [comment]
You can obtain this pull request as a local branch
Make sure you have a local branch master that is up-to-date with the lcgeo master branch
Assuming origin is the remote poiting to the ilcsoft/lcgeo
```
git fetch origin pull/30/head:ecalUpdate ## creates a local branch of this pull request
git checkout ecalUpdate ## change to the new branch
git rebase master ## after having a clean master that is up-to-date
## fix the conflicts
## push and make new PR
```

**Comment by protopopescu** [comment]
Closed. See PR #34.

**Pull request closed without merging**
