### PR TITLE
Vxd cable

### PR DESCRIPTION
**Pull request by shaojunlu**
BEGINRELEASENOTES
- Update for ILD services cables
  - Implement VXD cable cone services.
  - Implement the VXD cable services into ILD_common_v01 and ILD_common_v02.
  - Comment out the services in ILD_o1_v05.
  - Remove the ILD services reference code (not necessary).
  - The SServices00 has been updated, and used by ILD.
  - Update the ILD VXD cable configuration by expert. 

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
This doesn't compile

**Comment by shaojunlu** [comment]
Sorry, I miss one.
I have removed the unnecessary ILD service code, which need the removed ILD services reference code.

**Comment by shaojunlu** [comment]
Now, this PR #126 passed all checks.

**Comment by gaede** [comment]
@shaojunlu can you please increase the are used for the VXD cables to 25*mm*mm in
`ILD/compact/ILD_common_v02/services_defs.xml` and in `ILD/compact/ILD_common_v01/services_defs.xml`

**Comment by danieljeans** [comment]
@shaojunlu 

At the moment, the material for the VTX and FTD cables is added to the beampipe in the second cone. I have not read your code carefully, but I just want to be sure that we are not double counting this material by also adding it to the services driver.

As I understand it, currently (i.e. before this update) VXD cables are missing just between the VXD "cryostat" and the second cone of the beampipe (i.e. 150mm<|z|<230mm). I believe that other VXD and FTD cables are accounted for. 

I am not against putting all of these VXD/FTD cables into the service driver (in fact I think it's better), but we should remove the extra material from the beampipe.

**Comment by shaojunlu** [comment]
@gaede the compact files has been updated with new VXD cable number.
@andresailer  but it pass the check for gcc, and failed for llvm, what is wrong for llvm test?

**Comment by andresailer** [comment]
Slight issue with the nightly for llvm, will be fixed very soon

**Comment by petricm** [comment]
Fixed. However the validity of the tests today is dubious, since @gaede merged a broken DD4hep (AIDASoft/DD4hep#199), all tests of today are based on this broken DD4hep.

**Pull request merged**
