### PR TITLE
Added correct tracker region to SiD models

### PR DESCRIPTION
**Pull request by protopopescu**
Added tracker region to SiD models as requested by #81
BEGINRELEASENOTES
- Added correct tracker region to SiD models
- changed tests to use SiD_o2_v02
- Added detector type flags to ECalBarrel v03
- Other minor edits
ENDRELEASENOTES

### CODE REVIEW

**Comment by protopopescu** [comment]
I cannot merge pull requests anymore ... 
What's this thing with reviews?

**Comment by protopopescu** [comment]
Thanks, Marko! 
However, please note that I cannot merge it myself, because the button is greyed-out ...

**Comment by petricm** [comment]
We are waiting for the test to pass

**Comment by andresailer** [comment]
You need to rebase your branch to the lcgeo master

**Comment by protopopescu** [comment]
On my screen it says ready to merge.

**Comment by gaede** [comment]
If you reload the web page it will say:
**This branch cannot be rebased due to conflicts**

**Comment by protopopescu** [comment]
I don't know what's going on, but it does not say anything like that. It says 'Changes Approved', 'All checks have passed', and 'This pull request can be automatically merged by project collaborators'
'Only those with write access to this repository can merge pull requests.'

**Comment by petricm** [comment]
You are making a PR from a a branch that is 7 commits ahead and 46 commits behind lcgeo:master, therefore there are conflicts. 
screen shot 2017-04-06 at 12 45 40 pm

**Comment by andresailer** [comment]
I've send a message to github support about the difference in the status messages.

**Comment by protopopescu** [comment]
Ok. Now I see that we see different status messages. 
screen shot 2017-04-06 at 13 01 42
But how to proceed from here?

**Comment by andresailer** [comment]
You rebase your branch to the lcgeo master

**Comment by protopopescu** [comment]
I don't see such option on the GitHub interface that I'm presented with. If you see the rebase button, Andre or Marko, could you please click it to get this done and out of the way?

**Comment by andresailer** [comment]
Dan, there is no such button. You need to use a terminal to rebase your branch to the ilcsoft/lcgeo master branch.

**Comment by andresailer** [comment]
@gaede, @petricm I heard back from github support, the different messages for us and Dan are, at the moment at least, expected behaviour Thus if there are PRs in the future that show "This branch cannot be rebased due to conflicts" we should write this as a comment in the PR because it might not be visible to the PR creator.

**Pull request closed without merging**
