### PR TITLE
Create SiD_o2_v04

### PR DESCRIPTION
**Pull request by protopopescu**
BEGINRELEASENOTES
- Added SiD_o2_v04, which is an updated version of o2_v03, containing a few fixes, among which
    - correct size and position of ECal layer 0 via new driver ECalBarrel_o2_v04_geo.cpp
    - new beam pipe by Chris Potter
    - removed brass HCal option

ENDRELEASENOTES

### CODE REVIEW

**Comment by protopopescu** [comment]
Thanks Andre, for changing the name and keeping an eye on this. I've committed all changes I wanted to do at this time, so this is ready for merging from my point of view.

**Comment by protopopescu** [comment]
Who's supposed to approve this merge?

**Review by andresailer — APPROVED** [review]

**Comment by andresailer** [comment]
Whats the new thing for ECalBarrel_o2_v04_geo.cpp?

**Comment by protopopescu** [comment]
Hi Andre. This v04 driver implements a corrected ECal layer 0 size and position, as requested by UOregon.

**Pull request merged**
