### PR TITLE
update/corrections for SDHCAL

### PR DESCRIPTION
**Pull request by TiborILD**
BEGINRELEASENOTES
- reverse ordering of slices in Barrel, Endcaps_v01
- correction for z-cracks in Barrel
- towers numbering from inner to outer radius (Endcaps_v02)
- staves numbering 0-3 (Endcaps_v02) 
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Please fix the warning for the now unused variable.
https://travis-ci.org/iLCSoft/lcgeo/jobs/235257953#L749

**Comment by TiborILD** [comment]
Hi Andre, 
Yes, it's fixed. 

thanks 
Tibor 


De: "Andre Sailer" <notifications@github.com> 
À: "iLCSoft/lcgeo" <lcgeo@noreply.github.com> 
Cc: "TiborILD" <kurca@in2p3.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 23 Mai 2017 18:08:07 
Objet: Re: [iLCSoft/lcgeo] update/corrections for SDHCAL (#105) 



Please fix the warning for the now unused variable. 
[ https://travis-ci.org/iLCSoft/lcgeo/jobs/235257953#L749 | https://travis-ci.org/iLCSoft/lcgeo/jobs/235257953#L749 ]

**Comment by andresailer** [comment]
You need to push your updated branch

**Comment by TiborILD** [comment]
well, I am confused. I have seen my last 2 commits here, in total there were 1401 commits. Now there are only 1399 commits and my 2 last commits disappeared....
  What went wrong? What did I messed up?

**Comment by andresailer** [comment]
Here are 1401 commits https://github.com/TiborILD/lcgeo/tree/mySDHCAL
here are 1399 commits: https://github.com/iLCSoft/lcgeo

**Comment by TiborILD** [comment]
I see, but somehow I am not able to push those 2 additional commits: 

% git push --force downstream mySDHCAL 
Password: 
Everything up-to-date 



De: "Andre Sailer" <notifications@github.com> 
À: "iLCSoft/lcgeo" <lcgeo@noreply.github.com> 
Cc: "TiborILD" <kurca@in2p3.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 26 Mai 2017 11:09:49 
Objet: Re: [iLCSoft/lcgeo] update/corrections for SDHCAL (#105) 



Here are 1401 commits [ https://github.com/TiborILD/lcgeo/tree/mySDHCAL | https://github.com/TiborILD/lcgeo/tree/mySDHCAL ] 
here are 1399 commits: [ https://github.com/iLCSoft/lcgeo | https://github.com/iLCSoft/lcgeo ]

**Comment by andresailer** [comment]
What do you get in your local working directory for these commands?
```
git remote -v
git branch -vv
git status
```

**Comment by TiborILD** [comment]
% git remote -v 
downstream https://TiborILD@github.com/TiborILD/lcgeo.git (fetch) 
downstream https://TiborILD@github.com/TiborILD/lcgeo.git (push) 
origin https://github.com/iLCSoft/lcgeo.git (fetch) 
origin https://github.com/iLCSoft/lcgeo.git (push) 
% git branch -vv 
master 423e921 [origin/master] Remove CLIC_o3_v09 and CLIC_o3_v10 from test and replace with CLIC_o3_v11 which is nearly identical to the other two with only tiny xml differences 
masterBackup 2eea832 [origin/master: ahead 32, behind 157] Hcal_Endcaps_SD_v01.xml : cleaning & typo correction 
masterBackup2 819a2ad [origin/master: behind 142] switch back to constant B-field for ILD_o1_v05 
masterBackup3 6fcd5ff [origin/master: behind 92] Unchanged from o2_v02 
masterBackup4 423e921 [origin/master] Remove CLIC_o3_v09 and CLIC_o3_v10 from test and replace with CLIC_o3_v11 which is nearly identical to the other two with only tiny xml differences 
masterBackup5 423e921 [origin/master] Remove CLIC_o3_v09 and CLIC_o3_v10 from test and replace with CLIC_o3_v11 which is nearly identical to the other two with only tiny xml differences 
masterBackupX 007c8f3 [origin/master: ahead 1] removed unused variables 
* mySDHCAL 0388f8a removed commented line 
mySDhcal 93908a4 Rename detector/SiTrackerEndcap_o2_v02ext_geo.cpp to detector/tracker/SiTrackerEndcap_o2_v02ext_geo.cpp 
% git status 
# On branch mySDHCAL 
nothing to commit (working directory clean) 



De: "Andre Sailer" <notifications@github.com> 
À: "iLCSoft/lcgeo" <lcgeo@noreply.github.com> 
Cc: "TiborILD" <kurca@in2p3.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 26 Mai 2017 13:06:24 
Objet: Re: [iLCSoft/lcgeo] update/corrections for SDHCAL (#105) 



What do you get in your local working directory for these commands? 
git remote -v
git branch -vv
git status

**Comment by andresailer** [comment]
Ok, this pull request is made with your `master` branch, not with your `mySDHCAL` branch.
Maybe just open a pull request from your `mySDHCAL` branch instead.
https://github.com/iLCSoft/lcgeo/compare/master...TiborILD:mySDHCAL?expand=1

**Comment by andresailer** [comment]
Superceded by #106

**Pull request closed without merging**
