### PR TITLE
My sdhcal

### PR DESCRIPTION
**Pull request by TiborILD**
some corrections and cleaning for  	Hcal_Endcaps_SD_v01.xml,  	ILD_l2_v01.xml,  	ILD_s2_v01.xml

### CODE REVIEW

**Comment by andresailer** [comment]
Instead of merging the master into your branch, please rebase your branch onto the master, otherwise one cannot incorporate your changes.
See https://github.com/andresailer/tutorial/blob/master/README.md#incorporating-upstream-changes-after-creating-the-branch-rebasing

**Comment by TiborILD** [comment]
seems that I messed something up ...
or is this OK ? What else should I do?
% git rebase master
Current branch mySDHCAL is up to date.
% git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 32 commits.
% git pull origin
Already up-to-date.
% git checkout mySDHCAL
Switched to branch 'mySDHCAL'
% git rebase master
Current branch mySDHCAL is up to date.

**Comment by TiborILD** [comment]
Here the outputs of requested commands:
% git --version
git version 1.7.6.4
% git branch -vv
  master   2eea832 [origin/master: ahead 32] Hcal_Endcaps_SD_v01.xml : cleaning & typo correction
* mySDHCAL 2eea832 Hcal_Endcaps_SD_v01.xml : cleaning & typo correction
  mySDhcal 93908a4 Rename detector/SiTrackerEndcap_o2_v02ext_geo.cpp to detector/tracker/SiTrackerEndcap_o2_v02ext_geo.cpp
% git remote -v
downstream      https://TiborILD@github.com/TiborILD/lcgeo.git (fetch)
downstream      https://TiborILD@github.com/TiborILD/lcgeo.git (push)
origin  https://github.com/iLCSoft/lcgeo.git (fetch)
origin  https://github.com/iLCSoft/lcgeo.git (push)

**Comment by andresailer** [comment]
Ok, the other commands should work, unless the git version is too old for them.
```
git checkout master
git branch -m masterBackup ## rename master branch to backupMaster
git checkout -t origin/master ## get the original master again, assuming origin remote points to ilcsoft/lcgeo
git checkout mySDHCAL
git rebase master
git push --force downstream mySDHCAL ## overwrite your remote branch
```

**Comment by TiborILD** [comment]
seems that this command went through:
git push --force downstream mySDHCAL

   Should I create new pull request also?

**Comment by andresailer** [comment]
No need to create a new pull request, this one is based on the branch, if you change the branch the PR gets updated

**Comment by gaede** [comment]
@sailer can you please update the DD4hep version that us used for Travis, so that we can check if the PRs build

**Comment by andresailer** [comment]
No, but I can move the GuineaPigReader to dd4hep so lcgeo builds again.

**Comment by gaede** [comment]
Why can you not update DD4hep - the API has changed and we cannot run CI w/o a current version of DD4hep.

**Comment by petricm** [comment]
There will be an update of the CI system in the next days so that it will rely on a nightly deployed build in cvmfs. This will then be fixed with that update. 

I would like to point out however that we agreed in https://github.com/iLCSoft/lcgeo/pull/15 that 
- However we eventually want to move this [GuineaPigReader] to DD4hep, once it is well tested and proven to work. It is just simpler to develop it in lcgeo for the time being.

I think we can agree that it is proven that it works, is it also tested well?

**Comment by gaede** [comment]
Yes, we agreed to move the GuineaPigReader to DD4hep eventually - once it is proven to work and well tested.  And this is exactly the problem: it is of course not well tested, as we are currently stuck with pending PRs in lcgeo, in particular with #42 directly affecting the way this reader is to be used and tested. The PR's are stuck because the CI is using an outdated version of DD4hep.

There are several ways to deal with this issue in general:
-  updated the CI frequently ( nightly ), so that API changes are propagated to dependent packages relatively fast
- ignore failed builds for PRs in the time between API changes and CI updates and merge PRs nevertheless
- not merge PRs until the CI is updated to reflect API changes and builds succeed
- move all code that is affected by an API change to the parent package
        - obviously not a realistic option

The cleanest and most efficient solution is clearly the first one - all others are work-arounds at best. As this affects very much the way we develop code together in iLCSoft  and we should discuss this in detail at the upcoming LC SW-expert meeting.

**Comment by andresailer** [comment]
As Marko said he is implementing nightly deployments.

**Comment by gaede** [comment]
Excellent. This was not clear from Marko's posting. 
So how do we proceed in the meantime ?
- can you move the  GuineaPigReader to DD4hep with preserving the history ?
- how would this affect the pending PRs ?
 - do they need to be

**Comment by andresailer** [comment]
a) Yes  Aidasoft/dd4hep#113, just need to drop it from lcgeo
b) Not at all, we just need to restart the the builds as the CI will rebase to target branch
c) no

**Comment by petricm** [comment]
The base installation for CI is updated, now taken from the nightly stream, there needs to be still some small changes. The CI jobs can be restated as soon the cvmfs is replicated.

**Comment by petricm** [comment]
But the travis web api is still experiencing problems...

**Comment by petricm** [comment]
All PRs are now working in CI

**Comment by petricm** [comment]
The CI now depends on the nightly iLCSoft build

**Pull request merged**
